
import uuid
import os


with open("docker-compose.yml", "w") as myfile:
    myfile.write("version: '3'")
    myfile.write("\n")
    myfile.write("services:")
    myfile.write("\n")
    myfile.write(" bitcoindev:")
    myfile.write("\n")
    myfile.write("  build: BitcoinDev")
    myfile.write("\n")
    myfile.write("  image: bitcoindev")
    myfile.write("\n")
    myfile.write(" bitcoinClient:")
    myfile.write("\n")
    myfile.write("  build: ClientBaseImage")
    myfile.write("\n")
    myfile.write("  image: bitcoinnode")
    myfile.write("\n")
    myfile.write(" a:")
    myfile.write("\n")
    myfile.write("  build: MasterBaseImage")
    myfile.write("\n")
    myfile.write("  image: bitcoinmnode")
    myfile.write("\n")
    myfile.write("  ports:")
    myfile.write("\n")
    myfile.write("   - 20000:18332")
    myfile.write("\n")
    myfile.write("  depends_on:")
    myfile.write("\n")
    myfile.write("  - bitcoindev")
    myfile.write("\n")
    os.system('mkdir info/trade0')
    os.system('echo "rpcuser=Node0\nrpcpassword=Node0\nrpcallowip=0.0.0.0/0\n" > info/trade0/bitcoin.conf')
    #portsNumber = 20000
    #backupport = 25000
    nodeName = uuid.uuid4()
    print "Node Name: "+str(nodeName)
    myfile.write(" "+str(nodeName)+":")
    myfile.write("\n")
    myfile.write("  image: bitcoinnode")
    myfile.write("\n")
    myfile.write("  ports:")
    myfile.write("\n")
    myfile.write("   - 19999:18332")
    myfile.write("\n")
    myfile.write("   - 24999:18333")
    #+str(portsNumber)
    myfile.write("\n")
    myfile.write("  networks:")
    myfile.write("\n")
    myfile.write("   - mybitcoinnetwork")
    myfile.write("\n")
    myfile.write("  deploy:")
    myfile.write("\n")
    myfile.write("   restart_policy:")
    myfile.write("\n")
    myfile.write("     condition: on-failure")
    myfile.write("\n")
    myfile.write("  volumes:")
    myfile.write("\n")
    myfile.write("   - /home/r/BitcoinCompose/info/trade0:/root/.bitcoin")
    myfile.write("\n");
    myfile.write("  depends_on:")
    myfile.write("\n")
    myfile.write("   - a")
    myfile.write("\n")
    myfile.write("networks:")
    myfile.write("\n")
    myfile.write(" mybitcoinnetwork:")
    myfile.write("\n")
    myfile.write("  external:")
    myfile.write("\n")
    myfile.write("    name: mybitcoin")
    myfile.write("\n")

